### ISSUE TITLE
Assistance needed to add "Vibrancy" to VSCode Command Palette

### ISSUE THREAD

**Issue by mkanet** [EYHN/vscode-vibrancy#13]
I would like to add transparency effect to **Command Palette** and also customize colors that are only available in CSS.  I'm not very experienced with CSS.  Could someone be kind enough to offer a working code on how to do this?  I can make it transparent.  However, it does NOT have blur.

**Dark (Only Subbar).css**

     .monaco-workbench,
     .monaco-workbench .sidebar,
     .monaco-workbench .activitybar,
     .monaco-workbench .titlebar,
     .monaco-workbench .monaco-quick-open-widget,  /* I added this line */
     body {
          background: transparent !important;
     }

**Comment by mkanet** [comment]
I can also put the below setting in my settings.json file or in my theme extension.  However, it still shows transparency **without** blur:

     "quickInput.background": "#414141f3",

**Comment by EYHN** [comment]
Has been fixed in 1.5

**Comment by mkanet** [comment]
Thanks EYHN,
I just tried it again using the latest release of Vibrancy.  It doesn't look like it is fixed:
![monaco-quick-open-widget](https://user-images.githubusercontent.com/811008/64470302-0d965900-d0f6-11e9-831c-787431f7e5fd.png)

**Comment by EYHN** [comment]
Sorry. I understand your question.

The following CSS adds '0.3' opacity for Command Palette.

```css
.monaco-quick-open-widget {
  background-color: rgba(37, 37, 38, 0.3) !important;
}
```

**Comment by mkanet** [comment]
There still isn't a blur effect.  Only standard transparency.  I can add blur effect to any background, except for the quick open widget.  Are you able to do it?

![NoVibrancyEffect](https://user-images.githubusercontent.com/811008/64471487-193e4b80-d107-11e9-8e7e-fb4bb31f795b.png)

**Comment by mkanet** [comment]
@EYHN, I'm curious were you ever able to successfully add acrylic blur effect to this?  Maybe, it's impossible?  I can only get normal transparency.  This is the only element I can't change using Vibrancy CSS.

**Comment by EYHN** [comment]
What this extension does is add a blur effect to the entire vscode window, if you wish to add another layer's blur effect to a specific element, it is recommended that you use the backdrop-filter property of css, Here is the example. https://codepen.io/huaji/pen/ExNVdKg

**Comment by mkanet** [comment]
Thank you for explaining @EYHN.  I added the below code to Vibrancy's custom CSS file; however, it didn't make any difference at all.  Could you please let me know the correct way to do it?  Maybe I'm specifying the wrong element name?

```
.monaco-quick-open-widget {
  background-color: rgba(37, 37, 38, 0.8) !important;
 -webkit-backdrop-filter: blur(10px);
  backdrop-filter: blur(10px);
}
```
